name: Failure to Issue
on:
  workflow_run:
    workflows: ["CI","E2E","Lighthouse","Deploy — Azure Static Web Apps"]
    types: [completed]
permissions:
  contents: write
  issues: write
  pull-requests: write
jobs:
  followup:
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Open tracking issue
        id: open
        uses: actions-ecosystem/action-create-issue@v1
        with:
          title: "Build failure: ${{ github.event.workflow_run.name }} (#${{ github.event.workflow_run.run_number }})"
          body:  "Run: ${{ github.event.workflow_run.html_url }}\nBranch: ${{ github.event.workflow_run.head_branch }}\n\nPlease investigate."
          labels: "broken,windsorfollowup"

      - name: Append follow-up task to AGENT_TASKS.md
        run: |
          f=AGENT_TASKS.md
          [ ! -f "$f" ] && printf '# Agent Tasks (source of truth)\n\n## Queue\n\n## Done\n' > "$f"
          printf -- "- [ ] Investigate CI failure: %s — %s\n" "${{ github.event.workflow_run.name }}" "${{ github.event.workflow_run.html_url }}" > .queue_add
          awk 'BEGIN{p=0} /^## Queue/ && !p {print; system("cat .queue_add"); p=1; next} {print}' "$f" > "$f.new"
          mv "$f.new" "$f"

      - name: Commit to a new branch and push
        env:
          BRANCH: ws-ci-fail/${{ github.run_id }}
        run: |
          git config user.name "ci-guardrails"
          git config user.email "actions@users.noreply.github.com"
          git checkout -b "$BRANCH"
          git add AGENT_TASKS.md
          git commit -m "chore(queue): CI failure follow-up"
          git push origin "$BRANCH"

      - name: Open PR and add automerge label
        uses: actions/github-script@v7
        env:
          RUN_ID: ${{ github.run_id }}
        with:
          script: |
            const { owner, repo } = context.repo
            const base = context.payload.repository.default_branch
            const head = `ws-ci-fail/${process.env.RUN_ID}`
            const title = `chore(queue): CI failure follow-up`
            const { data: pr } = await github.rest.pulls.create({ owner, repo, head, base, title, body: 'Auto-generated from failing run.' })
            await github.rest.issues.addLabels({ owner, repo, issue_number: pr.number, labels: ['automerge'] })
