name: Deploy — Azure Static Web Apps

on:
  push:
    branches: ['main']           # only deploy prod from main
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: swa-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.19.0'
          cache: 'pnpm'
          cache-dependency-path: 'pnpm-lock.yaml'

      - name: Install
        run: pnpm install --frozen-lockfile

      - name: Generate static site
        run: |
          pnpm run -s generate || pnpm run -s build
          test -d .output/public

      - name: Expose build metadata
        run: |
          echo "NUXT_PUBLIC_BUILD_SHA=${GITHUB_SHA}" >> $GITHUB_ENV
          echo "NUXT_PUBLIC_BUILD_BRANCH=${GITHUB_REF_NAME}" >> $GITHUB_ENV
          echo "NUXT_PUBLIC_BUILD_TIME=$(date -u +%Y-%m-%dT%H:%M:%SZ)" >> $GITHUB_ENV

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: 'upload'
          app_location: '.'
          output_location: '.output/public'
          skip_app_build: true   # we already built generated static files
