name: Deploy to Azure Static Web Apps

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node 20.19.x
        uses: actions/setup-node@v4
        with:
          node-version: '20.19.0'
          cache: 'npm'

      - name: Install deps (clean)
        run: npm ci

      - name: Build static Nuxt output
        run: |
          npm run build
        # Project root is repo root (Nuxt srcDir is 'app'); no working-directory needed

      - name: Sanity check build artifacts
        run: |
          test -f .output/public/index.html || (echo "No index.html in .output/public" && exit 1)
          ls -la .output/public | head -n 50

      - name: Deploy to Azure SWA (prebuilt, skip Oryx)
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "upload"
          app_location: ".output/public"     # point directly to built artifacts
          skip_app_build: true
          is_static_export: true
