name: Azure Static Web Apps CI/CD
# Disabled automatic triggers to prevent duplicate deployments. Use only for manual runs if needed.
on:
  workflow_dispatch:

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Legacy SWA workflow disabled; use 'Deploy to Azure Static Web Apps' workflow instead."
