name: Deploy — Azure Static Web Apps

on:
  push:
    branches: ['main']         # production deploys
    paths-ignore:
      - '**.md'
      - '.github/**'
  pull_request:                 # preview envs for PRs into main
    branches: ['main']
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: swa-${{ github.event_name }}-${{ github.ref || github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.19.0'
          cache: 'pnpm'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install
        run: pnpm install --frozen-lockfile

      - name: Generate static site
        run: |
          pnpm run -s generate || pnpm run -s build
          test -d .output/public

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: 'upload'
          app_location: '.'
          output_location: '.output/public'
          skip_app_build: true   # we already generated static files
