name: CI

on:
  push:
    branches: ['**']             # run on pushes to any branch
  pull_request:                  # run on PRs (any src) targeting any branch
    branches: ['**']
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.19.0'
          cache: 'pnpm'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm run -s lint || echo "no lint script"

      - name: Typecheck
        run: pnpm run -s typecheck || echo "no typecheck script"

      - name: Test
        run: pnpm run -s test || echo "no tests"

      # Nuxt 3 static output goes to .output/public (per project brief)
      - name: Build (generate static)
        run: |
          pnpm run -s generate || pnpm run -s build
          test -d .output/public

      - name: Upload site artifact
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: briko-site
          path: .output/public
          if-no-files-found: error
