name: Enable Auto-Merge
on:
  pull_request:
    types: [labeled, opened, reopened, synchronize]
permissions:
  pull-requests: write
  contents: write
jobs:
  enable:
    if: contains(github.event.pull_request.labels.*.name, 'automerge')
    runs-on: ubuntu-latest
    steps:
      - name: Enable PR auto-merge (squash)
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
        run: gh pr merge --auto --squash "$PR_URL"
