name: Failure to Issue
on:
  workflow_run:
    workflows: ["CI","E2E","Lighthouse","Deploy to Azure SWA"]
    types: [completed]
permissions:
  contents: write
  issues: write
jobs:
  file-issue:
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Open issue
        uses: actions-ecosystem/action-create-issue@v1
        with:
          title: "Build failure: ${{ github.event.workflow_run.name }} (#${{ github.event.workflow_run.run_number }})"
          body:  "Run: ${{ github.event.workflow_run.html_url }}\nBranch: ${{ github.event.workflow_run.head_branch }}\n\nPlease investigate."
          labels: "broken,windsorfollowup"
      - name: Queue follow-up task
        run: |
          FILE=AGENT_TASKS.md
          [ ! -f "$FILE" ] && echo -e "# Agent Tasks (source of truth)\n\n## Queue\n\n## Done" > "$FILE"
          ins="- [ ] Investigate CI failure: ${{ github.event.workflow_run.name }} — ${{ github.event.workflow_run.html_url }}"
          awk -v ins="$ins" 'BEGIN{p=0} /^## Queue/ && !p {print; print ins; p=1; next} {print}' "$FILE" > "$FILE.tmp" && mv "$FILE.tmp" "$FILE"
      - run: |
          git config user.name "ci-guardrails"
          git config user.email "actions@users.noreply.github.com"
          git add AGENT_TASKS.md
          git commit -m "chore: queue CI failure task" || true
          git push
