name: Nightly Health Check
on:
  schedule: [{ cron: "0 8 * * *" }]
  workflow_dispatch:
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Probe URLs
        run: |
          set -e
          curl -fsS https://briko.app/ > /dev/null
          curl -fsS https://briko.app/mosaic > /dev/null
          curl -fsS https://briko.app/voxel > /dev/null
      - name: If failed, open issue
        if: failure()
        uses: actions-ecosystem/action-create-issue@v1
        with:
          title: "Nightly health check failed"
          body: "One or more prod routes returned non-200. Please investigate."
          labels: "ops,windsorfollowup"
