name: Lighthouse
on: [pull_request]
jobs:
  lhci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: "20.19.0", cache: "npm" }
      - run: npm ci
      - run: npm run build:static
      - run: npm run serve:static &
      - run: npx wait-on http://localhost:4178
      - run: |
          npx lhci autorun \
            --collect.url=http://localhost:4178/ \
            --collect.url=http://localhost:4178/mosaic \
            --assert.assertions.performance=off \
            --assert.assertions."categories:performance">=0.85
