name: Stall Watch
on:
  schedule: [{ cron: "*/30 * * * *" }]
permissions:
  contents: read
  issues: write
jobs:
  stalled:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: top
        run: |
          head -n 200 AGENT_TASKS.md | awk '/^## Queue/{f=1;next} f && NF{print; exit}' > top.txt || true
          echo "TOP<<EOF" >> "$GITHUB_OUTPUT"
          cat top.txt >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"
      - uses: actions/github-script@v7
        with:
          script: |
            const top = `${{ steps.top.outputs.TOP }}`.trim()
            if (!top) return
            const since = 6 // hours
            const { owner, repo } = context.repo
            const { data: pulls } = await github.rest.pulls.list({ owner, repo, state: 'open' })
            const cutoff = Date.now() - since*3600*1000
            const active = pulls.some(p => new Date(p.updated_at).getTime() > cutoff)
            if (!active) {
              await github.rest.issues.create({
                owner, repo,
                title: "Queue stalled",
                body: `Top task:\n\n${top}\n\nNo PR activity in ${since}h. Windsurf may be offline.`,
                labels: ['stalled','windsorfollowup']
              })
            }
